---
- name: Deploy Java WAR Application to Docker
  hosts: docker-host
  become: true

  vars:
    app_name: ABCtechnologies-2
    dockerfile_content: |
      # Use an official Tomcat image as a parent image
      FROM tomcat:9.0

      # Copy the WAR file to the webapps directory of Tomcat
      COPY {{ app_name }}.war /usr/local/tomcat/webapps/

      # Expose the port Tomcat is running on
      EXPOSE 8080

      # Define the entrypoint
      CMD ["catalina.sh", "run"]

  tasks:
    - name: Install Docker
      ansible.builtin.package:
        name: docker
        state: present

    - name: Install Docker module for Python
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Create application directory
      ansible.builtin.file:
        path: /opt/{{ app_name }}
        state: directory

    - name: Write Dockerfile
      ansible.builtin.copy:
        content: "{{ dockerfile_content }}"
        dest: /opt/{{ app_name }}/Dockerfile

    - name: Copy WAR file
      ansible.builtin.copy:
        src: /path/to/your/{{ app_name }}.war
        dest: /opt/{{ app_name }}/{{ app_name }}.war
        owner: root
        group: root
        mode: 0755

    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ app_name }}"
        path: /opt/{{ app_name }}

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ app_name }}_container"
        image: "{{ app_name }}"
        state: started
        ports:
          - "8080:8080"
