---
- name: Deploy to Kubernetes
  hosts: localhost
  tasks:
    - name: Clone the Git repository
      git:
        repo: 'https://github.com/pablobarua1/IGP_Project.git'
        dest: '/tmp/IGP-project'
        version: 'master' 
      
    - name: Create Kubernetes Pod
      kubernetes.core.k8s:
        state: present
        pod_definition: "{{ lookup('file', '/tmp/IGP-project/pod.yml') }}"

    - name: Create Kubernetes Service
      kubernetes.core.k8s:
        state: present
        service_definition: "{{ lookup('file', '/tmp/IGP-project/service.yml') }}"

    - name: Create Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        deployment_definition: "{{ lookup('file', '/tmp/IGP-project/deployment.yml') }}"

