apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: mydockerhubusername/myapp:latest
    ports:
    - containerPort: 9090
