apiVersion: v1
kind: Pod
metadata:
  name: IGP-pod
  labels:
    app: IGPapp
spec:
  containers:
  - name: IGP-container
    image: darkknight7/igp_project:latest
    ports:
    - containerPort: 9090
